import Link from 'next/link';
import LegalLayout from '@/components/landing/LegalLayout';
import {
  LEGAL_LEAD, LEGAL_P, LEGAL_H2, LEGAL_STRONG, LEGAL_LI,
} from '@/components/landing/legalStyles';

export const metadata = {
  title: 'Terms & Conditions — GI Buddy',
  description: 'The terms that govern your use of GI Buddy, including the medical disclaimer and billing.',
};

const SECTIONS = [
  'Acceptance of terms',
  'Eligibility',
  'Description of the service',
  'Medical disclaimer',
  'Accounts and security',
  'Acceptable use',
  'Subscriptions and billing',
  'AI-generated content',
  'User content and licence',
  'Intellectual property',
  'Third-party services',
  'Termination',
  'Disclaimer of warranties',
  'Limitation of liability',
  'Indemnification',
  'Governing law and disputes',
  'Changes to these terms',
  'Contact',
];

export default function Page() {
  return (
    <LegalLayout
      title="Terms & Conditions" updated="17 August 2026"
      sections={SECTIONS} active="terms"
    >
      <p style={LEGAL_LEAD}>
        These terms govern your use of GI Buddy, operated by DSHG Sonic. Please read them together with the{' '}
        <Link href="/privacy-policy" className="lp-a" style={{ fontWeight: 600 }}>Privacy Policy</Link>.
      </p>

      <h2 id="s1" style={LEGAL_H2}>1. Acceptance of terms</h2>
      <p style={LEGAL_P}>
        By creating an account or using GI Buddy, you agree to these terms. If you do not agree, do not use the
        service.
      </p>

      <h2 id="s2" style={LEGAL_H2}>2. Eligibility</h2>
      <p style={LEGAL_P}>
        You must be 18 or over to hold an account. A minor may use GI Buddy only with the consent and
        supervision of a parent or guardian, who accepts these terms on their behalf.
      </p>

      <h2 id="s3" style={LEGAL_H2}>3. Description of the service</h2>
      <p style={LEGAL_P}>
        GI Buddy provides AI-assisted food checks by text, photo, voice and barcode; a diet profile; generated
        meal plans, grocery lists and recipes; a cuisine explorer; daily suggestions; a GI-scoped AI assistant;
        a colonoscopy prep planner; and a searchable recommendation history. Features may change as the product
        develops.
      </p>

      <h2 id="s4" style={LEGAL_H2}>4. Medical disclaimer</h2>
      <div style={{
        margin: '14px 0 0', border: '1.5px solid #e8edf2', borderRadius: 12,
        padding: 20, background: '#f8fafc',
      }}>
        <p style={LEGAL_LEAD}>
          GI Buddy provides general dietary information only. It is{' '}
          <strong style={LEGAL_STRONG}>not a medical device</strong>, it does not diagnose, treat, cure or
          prevent any condition, and it is{' '}
          <strong style={LEGAL_STRONG}>not a substitute for professional medical advice</strong>. Always follow
          the instructions of your physician or care team, in particular the colonoscopy-preparation
          instructions your clinic gave you. Seek immediate medical attention for severe symptoms such as
          intense abdominal pain, persistent vomiting, significant rectal bleeding, or signs of dehydration.
          Never delay or disregard clinical advice because of something you read in GI Buddy.
        </p>
      </div>

      <h2 id="s5" style={LEGAL_H2}>5. Accounts and security</h2>
      <p style={LEGAL_P}>
        You are responsible for the accuracy of your account and diet profile details and for keeping your
        credentials confidential. Tell us promptly if you suspect unauthorised access.
      </p>

      <h2 id="s6" style={LEGAL_H2}>6. Acceptable use</h2>
      <p style={LEGAL_P}>
        Do not misuse the service: no unlawful use, no attempts to reverse engineer, scrape or disrupt it, no
        uploading of content you have no right to share, no impersonation, and no use of the AI assistant to
        seek diagnosis or treatment decisions.
      </p>

      <h2 id="s7" style={LEGAL_H2}>7. Subscriptions, billing and auto-renewal</h2>
      <p style={LEGAL_P}>
        GI Buddy offers a Free tier with basic access, Premium Monthly at $9.99 per month, and Premium Yearly
        at $89.99 per year. Payments are processed by Stripe. Subscriptions renew automatically at the end of
        each term unless you cancel beforehand; auto-renew is on by default. You may cancel at any time from
        your account, and access continues to the end of the paid period. Except where required by law, payments
        already made are non-refundable. Prices may change with notice before your next renewal.
      </p>

      <h2 id="s8" style={LEGAL_H2}>8. AI-generated content and its limitations</h2>
      <p style={LEGAL_P}>
        Food checks, plans, recipes and assistant replies are generated by AI and may be inaccurate, incomplete
        or out of date — particularly with unclear photos, unlabelled dishes or incomplete ingredient
        information. The assistant is scoped to GI health and nutrition and will decline unrelated questions.
        Verify anything important with your care team before acting on it.
      </p>

      <h2 id="s9" style={LEGAL_H2}>9. User content and licence granted</h2>
      <p style={LEGAL_P}>
        You keep ownership of the content you submit — profile details, photos, voice recordings, messages and
        lists. You grant us a limited licence to host, process and transmit it to our processors for the purpose
        of operating the service and generating your recommendations.
      </p>

      <h2 id="s10" style={LEGAL_H2}>10. Intellectual property</h2>
      <p style={LEGAL_P}>
        GI Buddy, its software, design, and trade marks belong to DSHG Sonic or its licensors. You receive a
        personal, non-transferable, revocable licence to use the app for its intended purpose.
      </p>

      <h2 id="s11" style={LEGAL_H2}>11. Third-party services</h2>
      <p style={LEGAL_P}>
        The service relies on third parties including our AI provider, Stripe, hosting and email providers.
        Their own terms apply to their services, and we are not responsible for their acts or omissions beyond
        our contractual arrangements with them.
      </p>

      <h2 id="s12" style={LEGAL_H2}>12. Termination</h2>
      <p style={LEGAL_P}>
        You may stop using GI Buddy and delete your account at any time. We may suspend or terminate access if
        you breach these terms, or where necessary for legal or security reasons.
      </p>

      <h2 id="s13" style={LEGAL_H2}>13. Disclaimer of warranties</h2>
      <p style={LEGAL_P}>
        The service is provided &quot;as is&quot; and &quot;as available&quot;, without warranties of any kind
        to the fullest extent permitted by law, including fitness for a particular purpose or that AI output
        will be accurate or uninterrupted.
      </p>

      <h2 id="s14" style={LEGAL_H2}>14. Limitation of liability</h2>
      <p style={LEGAL_P}>
        To the extent permitted by law, DSHG Sonic is not liable for indirect, incidental or consequential
        losses, and our total liability is limited to the amount you paid for the service in the twelve months
        before the claim. Nothing here excludes liability that cannot lawfully be excluded.
      </p>

      <h2 id="s15" style={LEGAL_H2}>15. Indemnification</h2>
      <p style={LEGAL_P}>
        You agree to indemnify DSHG Sonic against claims arising from your misuse of the service or breach of
        these terms.
      </p>

      <h2 id="s16" style={LEGAL_H2}>16. Governing law and dispute resolution</h2>
      <p style={LEGAL_P}>
        TODO: set the governing law and forum with counsel. These terms are governed by the laws of
        [jurisdiction], and disputes will be resolved in the courts of [jurisdiction], without prejudice to your
        mandatory local consumer rights.
      </p>

      <h2 id="s17" style={LEGAL_H2}>17. Changes to these terms</h2>
      <p style={LEGAL_P}>
        We may update these terms. Material changes will be notified in the app or by email before they take
        effect, and the date at the top of this page will change.
      </p>

      <h2 id="s18" style={LEGAL_H2}>18. Contact</h2>
      <p style={LEGAL_P}>TODO: replace with the real contact details.</p>
      <div style={{ margin: '14px 0 0', display: 'grid', gap: 8 }}>
        <span style={LEGAL_LI}>
          Email <a href="mailto:gibuddy356@gmail.com" className="lp-a" style={{ fontWeight: 600 }}>
            gibuddy356@gmail.com
          </a>
        </span>
        <span style={LEGAL_LI}>
          Phone <span style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: 14, color: '#0f172a' }}>
            ---------------------
          </span>
        </span>
        <span style={LEGAL_LI}>---------------------</span>
      </div>
    </LegalLayout>
  );
}
